name: Pa11y CI

on: [push]

jobs:
  pa11y:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install Pa11y
        run: npm install pa11y-ci
      - name: run Pa11y
        run: npm pa11y-ci
