name: Pa11y CI

on: [push]

jobs:
  pa11y:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Run Pa11y
        run: npm run pa11y-ci
